In [1]:
1 + 1

2

## Podstawy NumPy

### Import biblioteki NumPy

In [2]:
import numpy as np

Tablica 1D

In [4]:
arr1d = np.array([1, 2])
arr1d

array([1, 2])

In [5]:
type(arr1d)

numpy.ndarray

Tablica 2D

In [6]:
arr2d = np.array([[1, 2], [3, 4]])
arr2d

array([[1, 2],
       [3, 4]])

Tablica 3D

In [9]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Wymiar tablicy

In [10]:
arr1d.ndim

1

In [11]:
arr2d.ndim

2

In [12]:
arr3d.ndim

3

Kształ tablicy

In [13]:
arr1d.shape

(2,)

In [14]:
arr2d.shape

(2, 2)

In [15]:
arr3d.shape

(2, 2, 2)

Typy danych

In [16]:
arr1d.dtype

dtype('int32')

In [17]:
arr2d.dtype

dtype('int32')

In [18]:
arr3d.dtype

dtype('int32')

In [19]:
arr_float = np.array([1.1, 2.2])
arr_float

array([1.1, 2.2])

In [20]:
arr_float.dtype

dtype('float64')

In [21]:
arr_bool = np.array([True, False])
arr_bool

array([ True, False])

In [22]:
arr_bool.dtype

dtype('bool')

Jawne deklarowanie typu

In [23]:
arr_int = np.array([1.5, 2.2], dtype='int')
arr_int

array([1, 2])

In [24]:
arr_int.dtype

dtype('int32')

### Funkcje tworzące tablice

arange

In [25]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1, 20, 3)

array([ 1,  4,  7, 10, 13, 16, 19])

zeros

In [28]:
np.zeros(3)

array([0., 0., 0.])

In [29]:
np.zeros([2, 3])

array([[0., 0., 0.],
       [0., 0., 0.]])

ones

In [30]:
np.ones(2)

array([1., 1.])

In [32]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

linspace

In [33]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [34]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### Podstawowe operacje na tablicach

In [35]:
a = np.array([3, 4, 5, 6])
b = np.array([-1, 3, 1, -2])

In [36]:
print(a)
print(b)

[3 4 5 6]
[-1  3  1 -2]


In [37]:
a + b

array([2, 7, 6, 4])

In [38]:
a - b

array([4, 1, 4, 8])

In [39]:
a * b

array([ -3,  12,   5, -12])

In [40]:
a / b

array([-3.        ,  1.33333333,  5.        , -3.        ])

In [41]:
a + 1

array([4, 5, 6, 7])

### Generowanie liczb pseudolosowych

In [42]:
np.random.seed(5)

Rozkład normalny

In [43]:
np.random.randn()

0.44122748688504143

0 - 1

In [44]:
np.random.rand()

0.20671915533942642

In [45]:
np.random.randn(10)

array([-0.33087015, -0.02330375,  0.84177767,  1.36758552,  0.57470769,
       -1.88576241,  0.17092537, -0.40309331,  1.63762849, -0.60529785])

In [46]:
np.random.rand(10)

array([0.29607993, 0.62878791, 0.57983781, 0.5999292 , 0.26581912,
       0.28468588, 0.25358821, 0.32756395, 0.1441643 , 0.16561286])

Losowanie liczba całkowitych

In [49]:
np.random.randint(10, 20, 20)

array([19, 16, 10, 15, 12, 18, 16, 18, 10, 15, 12, 10, 17, 17, 16, 10, 10,
       18, 15, 15])

mieszanie w tablicy

In [51]:
c = np.array([1, 2, 3, 4, 5, 6])
c

array([1, 2, 3, 4, 5, 6])

In [53]:
np.random.shuffle(c)
c

array([3, 2, 1, 5, 4, 6])

Losowa wartość z tablicy

In [54]:
np.random.choice(['a', 'b', 'c', 'd'])

'd'