In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 16)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Wybór elementów po indeksie

In [3]:
arr[2]

3

Wybór elementów w zakresie

In [4]:
arr[2:5]

array([3, 4, 5])

In [5]:
arr[:8]

array([1, 2, 3, 4, 5, 6, 7, 8])

Przypisywanie nowej wartości

In [6]:
arr[0] = 100
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [7]:
arr[10:12] = 200
arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200, 200,  13,
        14,  15])

Tablica 2D

Zmiana kształtu

In [8]:
arr2d = np.arange(1, 16).reshape([3, 5])
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
arr2d[1]

array([ 6,  7,  8,  9, 10])

In [10]:
arr2d[1][1]

7

In [11]:
arr2d[1:, 1:4]

array([[ 7,  8,  9],
       [12, 13, 14]])

Selekcja - maska logiczna

In [14]:
arr_rnd = np.random.randn(3, 5)
arr_rnd

array([[-0.43204548,  0.03697357, -0.50465649, -1.08399649,  1.21245481],
       [ 1.08532552,  0.37869355,  0.4713245 ,  1.69767815, -0.54847249],
       [ 0.49267193,  1.6274577 , -0.34607262,  0.77144662,  0.24208566]])

In [15]:
arr_rnd_bool = arr_rnd > 0
arr_rnd_bool

array([[False,  True, False, False,  True],
       [ True,  True,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [20]:
arr_rnd[arr_rnd_bool]

array([0.03697357, 1.21245481, 1.08532552, 0.37869355, 0.4713245 ,
       1.69767815, 0.49267193, 1.6274577 , 0.77144662, 0.24208566])

In [23]:
arr_rnd[arr_rnd < 0]

array([-0.43204548, -0.50465649, -1.08399649, -0.54847249, -0.34607262])